"""Add category_id to books table

Revision ID: 225c005ca9b9
Revises: 57afba32a13f
Create Date: 2024-02-07 21:12:48.904203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225c005ca9b9'
down_revision = '57afba32a13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
