"""Add image_url column to books table

Revision ID: 57afba32a13f
Revises: 7e92c852abe8
Create Date: 2024-02-07 20:45:11.377588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57afba32a13f'
down_revision = '7e92c852abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
